### ISSUE TITLE
How to write WindIO

### ISSUE THREAD

**Issue by James-Ilosta** [IEAWindTask37/windIO#10]
Hi,

Is there a package or a set of options that I can use to open, modify and write WindIO files? I've tried using the ruamel.yaml package to modify a yaml file that has a windIO format and it changes the format of specific parameters. It transposes certain variables and renames others. For example:

grid: [0.0, 0.4, 0.8,  1.0]

becomes:

grid: 
- 0.0 
- 0.4
- 0.8
- 1.0

**Comment by gbarter** [comment]
The WindIO project really just aims to define the ontology / parameterization and not push any particular tool or workflow.  If it helps, there are some python tools for the WindIO schema in WISDEM [here](https://github.com/WISDEM/WISDEM/blob/master/wisdem/inputs/validation.py).

For the example you showed, putting an array of numbers in brackets or sub-bullets is equivalent in yaml language, just a style thing.
