### ISSUE TITLE
Definitions of root, joint, bos, and hub components 

### ISSUE THREAD

**Issue by mfekrysaidahmed** [IEAWindTask37/windIO#14]
Hi all
I noted that there are some components that are not properly defined in the following manual:
https://windio.readthedocs.io/en/latest/source/components.html

What are the bos, root and joint components? Are there any explanations for their fields?
The explication of the hub fields does not include:
`hub:

        flange_t2shell_t: 4.0
        flange_OD2hub_D: 0.5
        flange_ID2OD: 0.8
        hub_blade_spacing_margin: 1.2
        hub_stress_concentration: 2.5
        n_front_brackets: 3
        n_rear_brackets: 3
        clearance_hub_spinner: 0.5
        spin_hole_incr: 1.2
        pitch_system_scaling_factor: 0.54
        spinner_gust_ws: 70.0
        hub_material: steel #cast_iron
        spinner_material: ud
`

Can anyone provide me with some explanations?

Thanks in advance

**Comment by gbarter** [comment]
Hello and thank you for your interest and use of WindIO.  At this point, what is in WindIO for hub and drivetrain description is not a true "ontology" or common parameterization.  It is really just a copy-paste of inputs to [WISDEM](https://github.com/WISDEM/WISDEM) [DrivetrainSE](https://wisdem.readthedocs.io/en/master/wisdem/drivetrainse/index.html).  You can look there for some info on the inputs, but please don't interpret them as a template that other codes should adopt.  Better generalization and parameterization of the hub and nacelle components is on our long-term to-do list.  It is still unclear what that will look like or if it will include hub-blade root connection details.

**Comment by ptrbortolotti** [comment]
Hello,
as Garrett said, we'll have to work on the hub. As a small step, I unearthed the description of all those fields and they are now listed in the schema embedded in WISDEM, see here https://github.com/WISDEM/WISDEM/commit/bf1690932ff15b046dd43fa1e8bb070b3571450d

**Comment by mfekrysaidahmed** [comment]
Thank you all for your help
