### ISSUE TITLE
Publish windIO to package managers

### ISSUE THREAD

**Issue by rafmudaf** [IEAWindTask37/windIO#19]
`windIO` is currently not distributed via typical package managers for the Python ecosystem. For it to be used in other projects, it has to be included in the calling-project's source code. While the mechanisms to do this are straightforward, it is still cumbersome to put the infrastructure in place and time consuming to keep the package up to date. Instead, it would be simpler for projects to consume `windIO` similar to other libraries such as NumPy or YAML parsers. I propose to create an automated distribution system using GitHub Actions to package and upload `windIO` to PyPI and/or conda-forge.

If there is enough interest from the maintainers, I will add the infrastructure and create the pull request to do this.

FWIW This idea came from https://github.com/IEAWindTask37/windIO/pull/18#issuecomment-1709548831.

**Comment by rafmudaf** [comment]
@ptrbortolotti or other maintainers - do you support my implementing the suggestion in this issue?

**Comment by bayc** [comment]
@rafmudaf Yea, definitely support this! Thanks for offering to put this together.

**Comment by rafmudaf** [comment]
Resolved by #22
