### ISSUE TITLE
WindIO to AeroDyn15_blade format

### ISSUE THREAD

**Issue by TheMercer** [IEAWindTask37/windIO#56]
Hello,

Given that all the necessary data for blade geometry definition exist in the yaml file of the IEA-15/22MW turbine, how can I use the windIO toolchain (WEIS) to generate the AeroDyn15_blade.dat input files for these turbine?

Main problem is getting values for:
BlCrvAC        
BlSwpAC        
BlCrvAng

Best regards,
Kieran

**Comment by ptrbortolotti** [comment]
The tool [WEIS](https://github.com/WISDEM/WEIS) will generate the full OpenFAST model corresponding to a windIO yaml file. Example [06](https://github.com/WISDEM/WEIS/tree/develop/examples/06_IEA-15-240-RWT) might be a good start for the IEA15 reference wind turbine. 

If you are looking at the actual code, check out these [lines](https://github.com/WISDEM/WEIS/blob/86724c1f09b36a3698916a446ce988952e9e2969/weis/aeroelasticse/openmdao_openfast.py#L1041)

And just to make sure, both reference turbines come with the OpenFAST model available, so there is no need to run WEIS if you are only interested in the baseline designs of the [IEA15](https://github.com/IEAWindTask37/IEA-15-240-RWT/tree/master/OpenFAST) and [IEA22](https://github.com/IEAWindTask37/IEA-22-280-RWT/tree/main/OpenFAST).

**Comment by TheMercer** [comment]
Oh okay, 06 might be good example to get WindIO 2 Full OpenFast model.

As basically writing my own parsers. 

Thank you will look into this.

**Comment by TheMercer** [comment]
So does weis have functions that take Windio straight to full OpenFast models ?
