### ISSUE TITLE
Nomenclature for materials in windIO seems to have wrong indices

### ISSUE THREAD

**Issue by ewerthen** [IEAWindTask37/windIO#7]
https://windio.readthedocs.io/en/latest/source/materials.html

Indices for ultimate strength Xt11, Xt13, and Xt23 seem to be wrong. According to the defined directions for composites it should be Xt11, Xt22 and Xt33. Same for compression and thermal coefficient of expansion.
"For composites, direction 1 is aligned with the main fiber direction, direction 2 is in the plane transverse to the fibers, and direction 3 is perspendicular to the laminate plane"

**Comment by ptrbortolotti** [comment]
Hi ewerthen,
thank you, good catch! I've fixed the documentation now.
I close the issue now.
Regards,
Pietro

**Comment by ewerthen** [comment]
Hi Pietro,
no problem. It is a very good dataschema and very well documented, we have it in use!
Best regards
Edgar
